"""Add pass-secure

Revision ID: 964ed1c69cd5
Revises: df19fc248886
Create Date: 2020-05-04 14:37:03.888971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964ed1c69cd5'
down_revision = 'df19fc248886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
